/*
* generated by Xtext
*/
package ie.tcd.everm.evedsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class EveDescUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return ie.tcd.everm.evedsl.ui.internal.EveDescActivator.getInstance().getInjector("ie.tcd.everm.evedsl.EveDesc");
	}
	
}
