/*
 * generated by Xtext
 */
package ie.tcd.everm.evedsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EveDescExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ie.tcd.everm.evedsl.ui.internal.EveDescActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ie.tcd.everm.evedsl.ui.internal.EveDescActivator.getInstance().getInjector("ie.tcd.everm.evedsl.EveDesc");
	}
	
}
