/*
* generated by Xtext
*/
package ie.tcd.everm.evedsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EveDescAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("ie/tcd/everm/evedsl/parser/antlr/internal/InternalEveDesc.tokens");
	}
}
