/*
* generated by Xtext
*/
package ie.tcd.everm.evedsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import ie.tcd.everm.evedsl.services.EveDescGrammarAccess;

public class EveDescParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EveDescGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected ie.tcd.everm.evedsl.parser.antlr.internal.InternalEveDescParser createParser(XtextTokenStream stream) {
		return new ie.tcd.everm.evedsl.parser.antlr.internal.InternalEveDescParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "EventDesc";
	}
	
	public EveDescGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EveDescGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
