/*
 * generated by Xtext
 */
package ie.tcd.everm.evedsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EveDescUiModule extends ie.tcd.everm.evedsl.ui.AbstractEveDescUiModule {
	public EveDescUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
