/*
 * generated by Xtext
 */
package ie.tcd.everm.evedsl;

import org.eclipse.xtext.scoping.IScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EveDescRuntimeModule extends ie.tcd.everm.evedsl.AbstractEveDescRuntimeModule {
	public Class<? extends IScopeProvider> bindIScopeProvider() {
        return EveDescScopeProvider.class;
    }
	
}
