/*
* generated by Xtext
*/
package ie.tcd.everm.evedsl.ui.contentassist;

import ie.tcd.everm.evedsl.ui.contentassist.AbstractEveDescProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class EveDescProposalProvider extends AbstractEveDescProposalProvider {

}
