/*
* generated by Xtext
*/
package ie.tcd.everm.evedsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class EveDescOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
